### ISSUE TITLE
Fedora REST API ignores label and ownerID parameters

### ISSUE THREAD

**Issue by gkhom** [DANS-KNAW/easy-ingest#15]
When sending the label and ownerID properties as query parameters with an ingest request, Fedora seems to ignore these fields and leave them empty in the created digital object.

However, when these properties are specified in the FOXML, they are ingested properly. Thus a simple workaround is to specify these properties in the FOXML.

Example curl command to observe strange Fedora behaviour:

```
curl -v -H "Content-Type: text/xml" -H "Content-Disposition: attachment; filename=fo.xml" 
    -i -u fedoraAdmin:fedoraAdmin --data-binary @fo.xml 
    http://deasy:8080/fedora/objects/easy-test:10\?ownerId\=OwnerID+TEST\&label\=Label+TEST
```

This is the same type of request that the `yourmediashelf` library creates, resulting in the same behaviour.

**Comment by janvanmansum** [comment]
Seems to be a bug in Fedora.
