### ISSUE TITLE
Validate FOXML?

### ISSUE THREAD

**Issue by gkhom** [DANS-KNAW/easy-ingest#8]
Should we validate the FOXML in easy-ingest? Or can assume that the FOXML is valid? Or can we rely on Fedore to reject anything that isn't valid FOXML?

**Comment by janvanmansum** [comment]
Ik think we can rely on Fedora to reject invalid FOXML, but it would be a good idea to do a couple of simple tests to "validate" this claim.

**Comment by janvanmansum** [comment]
Won't fix
